from pathlib import Path
import sys

CURRENT_DIR = Path(__file__).resolve().parent
if str(CURRENT_DIR) not in sys.path:
    sys.path.insert(0, str(CURRENT_DIR))

from rag_service.app import app
from rag_service.config import Settings, settings
from rag_service.ingest import (
    create_ingest_job,
    expire_finished_ingest_jobs,
    ingest_worker,
    normalize_ingest_documents,
    parse_file_document,
    run_ingest,
)
from rag_service.metrics import count_cache_entries, increment_metric, metrics_snapshot
from rag_service.models import (
    AdminChunkResponse,
    AdminOverviewResponse,
    CacheStatsResponse,
    Citation,
    DocumentIn,
    ErrorResponse,
    FileDocumentIn,
    HistoryResponse,
    HistoryTurn,
    IngestJobQueuedResponse,
    IngestJobStatusResponse,
    IngestRequest,
    MetricsSummaryResponse,
    QueryRequest,
    QueryResponse,
)
from rag_service.rag import (
    admin_overview_counts,
    build_citations,
    build_prompt,
    cache_lookup,
    cache_store,
    embed,
    get_history,
    list_admin_chunks,
    llm_complete,
    llm_stream,
    rerank,
    retrieve,
    save_turn,
    stream_cached_answer,
)
from rag_service.state import AppState, state
from rag_service.utils import (
    compute_content_hash,
    cosine_similarity,
    decode_embedding,
    encode_embedding,
    filter_signature,
    log_event,
    normalize,
    split_document,
    utc_now,
    vec_to_string,
)

__all__ = [
    "AdminChunkResponse",
    "AdminOverviewResponse",
    "AppState",
    "CacheStatsResponse",
    "Citation",
    "DocumentIn",
    "ErrorResponse",
    "FileDocumentIn",
    "HistoryResponse",
    "HistoryTurn",
    "IngestJobQueuedResponse",
    "IngestJobStatusResponse",
    "IngestRequest",
    "MetricsSummaryResponse",
    "QueryRequest",
    "QueryResponse",
    "Settings",
    "admin_overview_counts",
    "app",
    "build_citations",
    "build_prompt",
    "cache_lookup",
    "cache_store",
    "compute_content_hash",
    "cosine_similarity",
    "count_cache_entries",
    "create_ingest_job",
    "decode_embedding",
    "embed",
    "encode_embedding",
    "expire_finished_ingest_jobs",
    "filter_signature",
    "get_history",
    "increment_metric",
    "ingest_worker",
    "list_admin_chunks",
    "llm_complete",
    "llm_stream",
    "log_event",
    "metrics_snapshot",
    "normalize",
    "normalize_ingest_documents",
    "parse_file_document",
    "rerank",
    "retrieve",
    "run_ingest",
    "save_turn",
    "settings",
    "split_document",
    "state",
    "stream_cached_answer",
    "utc_now",
    "vec_to_string",
]
